os: osx
osx_image: 
language: ruby
rvm:
  - 2.3.5
  - 2.5.3
  - 2.6.4
before_install:
  - gem install bundler || gem install bundler --version '< 2'
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - mysql -e 'create database sequel_test;'
  - psql -c 'create database sequel_test;' -U postgres
addons:
  postgresql: "9.6"
services:
  - postgresql
  - mysql
